name: example
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Jacob Phillips <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mdc_web_components:
    path: ..

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  sass_builder:
    git: https://github.com/jifalops/sass_builder
